### ISSUE TITLE
Your request body was malformed error

### ISSUE THREAD

**Issue by jstockwin** [mwthink/digitalocean-floating-ip-controller#1]
Hey! Thanks for your work on this, it certainly serves a purpose.

I'm having some issues, however:
```
>>> kubectl logs -n kube-system floating-ip-controller-XXXXXXXXXXX
jq: error (at <stdin>:1): null (null) only strings can be parsed
Attaching IP to droplet 
{"id":"bad_request","message":"Your request body was malformed."}Attaching IP to droplet 
jq: error (at <stdin>:1): null (null) only strings can be parsed
jq: error (at <stdin>:1): null (null) only strings can be parsed
{"id":"bad_request","message":"Your request body was malformed."}Attaching IP to droplet 
jq: error (at <stdin>:1): null (null) only strings can be parsed
{"id":"bad_request","message":"Your request body was malformed."}Attaching IP to droplet 
jq: error (at <stdin>:1): null (null) only strings can be parsed
{"id":"bad_request","message":"Your request body was malformed."}Attaching IP to droplet 
jq: error (at <stdin>:1): null (null) only strings can be parsed
{"id":"bad_request","message":"Your request body was malformed."}Attaching IP to droplet 
```

I've done some very minimal debugging by `exec`ing into the container, but am quite new to k8s etc. 

My suspicion is that there's an issue with the `NODE_SELECTOR` and related code - it looks like it ends up getting assigned wrong.

https://github.com/mwthink/digitalocean-floating-ip-controller/blob/master/main.sh#L10

It looks to me like:
- The URL is possibly getting a `?` added twice ([here](https://github.com/mwthink/digitalocean-floating-ip-controller/blob/master/main.sh#L10) and [here](https://github.com/mwthink/digitalocean-floating-ip-controller/blob/master/main.sh#L35))
- It also looks to me as though whatever the `NODE_SELECTOR` environment variable is, lines 10 to 13 set it to `labelSelector=?labelSelector`, but perhaps I am wrong.

Surely if `NODE_SELECTOR` is passed as an empty string then we should not add anything to the URL?

**Comment by mwthink** [comment]
Hey thanks for reporting this! Glad to see this project is getting some use.

Without having delved into the code recently, I can tell you I came across similar issues when I was initially writing it. It all has to do with the sloppy way the query string is built (Real ugly string concatenation). Writing this project in bash was really more of a proof-of-concept and I've been meaning to revisit it using either node or golang, haven't got around to that yet. With actual activity on this repo, I'm way more inclined to get a move on that.

All that being said, I'm going to keep this issue open for now until I actually write it in a real programming language, expect something from that by the end-of-week. Using a real request library instead of concating a curl command will resolve this and other issues. 

Any chance you could provide the label selector you are using? I'll include it as a test-case on a final implementation. 

If anyone wants to show off some bash-fu before this code is rewritten, feel free to submit a PR that would fix this issue and I will accept it. Personally, I'd just rather spend my time writing this thing properly than trying to enhance the sketchy-at-best bash implementation. 

Check back in 72 hours and I'd expect this problem to be gone!

**Comment by jstockwin** [comment]
Hey, thanks for the response and makes sense. I'd appreciate a quick bash fix anyway so maybe I'll look into it somehow.

I'm actually just passing `NODE_SELECTOR=""` as in the `deploy.yaml` ([here](https://github.com/mwthink/digitalocean-floating-ip-controller/blob/master/deploy.yaml#L58)). I don't need any label selector at all... so hopefully, we can get that case working.

If you experienced issues initially, did you come up with a workaround?

Writing it properly sounds like a good idea!
